version: 2
jobs:
  build:
    working_directory: ~/angular-travis
    docker:
      - image: circleci/node:12-browsers
    steps:
      - checkout
      

      - run:
          name: install-dependencies
          command: npm install 
      

      - run:
          name: angular-build
          command: npm run-script build
